/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kislovskiy.dates;

import org.junit.Test;

import java.text.ParseException;
import java.time.LocalDate;
import java.time.LocalDateTime;

import static com.kislovskiy.dates.App.compareDate;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class AppTest {
    @Test
    public void appHasAGreeting() throws ParseException {
        App classUnderTest = new App();
        assertEquals("app should return array of dates",
                8,
                App.printDates(LocalDate.of(2021, 10, 4)).size());
        assertEquals("app should return array of dateTimes",
                8,
                App.printDateTimes(
                        LocalDateTime.of(2021, 10, 4, 0, 0, 0)).size());
        assertEquals("app should parse Date",
                LocalDateTime.of(2021, 10, 4, 0, 0, 0),
                App.parseDate("2021-10-04 00:00:00"));
        assertTrue("app should compare dates",
                compareDate(LocalDateTime.of(2021, 10, 4, 0, 0, 0),
                        LocalDateTime.of(2021, 10, 10, 20, 23, 11)));
    }
}
