/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello;

public class HelloWorld {
    public static void main(String[] args) {
    Greeter greeter = new Greeter();
        System.out.println(greeter.sayHello(args));
    }
}
